"""The playbook (docs/B2-agent-generation-playbook.md) encoded as data.

The playbook is a **data artifact**: it instructs Role A harnesses, never this
tooling. What lives here is the machine-checkable half of that contract —
§0 inputs, the §6 layout, the §7 contract checklist — so certify (layer 7) and
the conformance fixtures (layer 12) validate candidates against one source of
truth. Layer 6's checklist IS playbook §7; it is not forked here.
"""
from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from typing import Literal

PLAYBOOK_VERSION = "3-beta"

# §6 artifact layout
MANIFEST_NAME = "AGENT_MANIFEST.yaml"
REQUIRED_FILES = (MANIFEST_NAME, "entry.draft.yaml", "SPEC.md", "REPORT.md")
REQUIRED_DIRS_B2B = ("src", "prompts", "tests", "eval", "trace")
REQUIRED_DIRS_B2A = ("scaffold", "eval")
ALLOWED_TOP_LEVEL = set(REQUIRED_FILES) | set(REQUIRED_DIRS_B2B) | set(REQUIRED_DIRS_B2A)

STATUSES = ("COMPLETE", "PARTIAL", "ERROR")
BINDABLE_KINDS = frozenset({"skill", "mcp-tool"})
FORBIDDEN_BINDING_KINDS = frozenset({"agent", "component", "a2a-agent"})

# UI is generated by the platform (UI-PLANE §1); candidates ship none (§8)
UI_SUFFIXES = (".html", ".htm", ".j2", ".jinja", ".jinja2", ".js", ".jsx",
               ".ts", ".tsx", ".css", ".scss", ".vue", ".svelte")

# playbook §7 — echoed verbatim; any false ⇒ status cannot be COMPLETE
CONTRACT_ITEMS: tuple[tuple[str, str], ...] = (
    ("criteria_refs_verbatim",
     "behavioral_criteria_ref (and interface_criteria_ref if full-agent) computed "
     "from the exact input texts, unmodified."),
    ("bindings_verbatim",
     "Every binding is kind: skill|mcp-tool, copied (id, version, schema_hash) "
     "verbatim from CAPABILITY_MANIFEST; zero invented tools."),
    ("no_agent_invocation",
     "No kind: agent|component|a2a-agent invoked or bound anywhere in src/."),
    ("no_ui_no_model_ids_no_secrets",
     "No UI files, no hardcoded model identifiers, no secrets in the candidate."),
    ("layout_exact",
     "Artifact layout matches §6 exactly; nothing written outside the candidate "
     "directory."),
    ("no_criterion_weakened",
     "No criterion test deleted, skipped, or weakened during iteration."),
)


def criteria_hash(text: str) -> str:
    """Refs are sha256 of the exact frozen input text (§6 manifest fields)."""
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


@dataclass
class HarnessInputs:
    """§0 inputs, injected per invocation. Missing input → MISSING_INPUT."""
    task_spec: str
    behavioral_criteria: str
    catalog_ref: str
    capability_manifest: dict                 # catalog.lock.yaml at catalog_ref
    trust_tier_ceiling: str
    mode: Literal["B2a", "B2b"]
    scope: Literal["full-agent", "delta"]
    model_profile: str
    harness: str
    target_runtime: str
    residual: str | None = None               # delta only
    nearest_templates: list[dict] = field(default_factory=list)

    def missing(self) -> list[str]:
        required = {
            "TASK_SPEC": self.task_spec,
            "BEHAVIORAL_CRITERIA": self.behavioral_criteria,
            "CATALOG_REF": self.catalog_ref,
            "CAPABILITY_MANIFEST": self.capability_manifest,
            "TRUST_TIER_CEILING": self.trust_tier_ceiling,
            "MODE": self.mode,
            "SCOPE": self.scope,
            "MODEL_PROFILE": self.model_profile,
            "HARNESS": self.harness,
            "TARGET_RUNTIME": self.target_runtime,
        }
        names = [name for name, value in required.items() if not value]
        if self.scope == "delta" and not self.residual:
            names.append("RESIDUAL")
        return names

    def bindable(self) -> list[dict]:
        """Entries the candidate may bind: skill|mcp-tool at or below ceiling."""
        from lockbuild.trust import TIER_ORDER
        ceiling = TIER_ORDER[self.trust_tier_ceiling]
        return [
            e for e in self.capability_manifest.get("entries", [])
            if e.get("kind") in BINDABLE_KINDS
            and TIER_ORDER.get(e.get("trust_tier", "untrusted"), 0) >= ceiling
            and not e.get("stale")
        ]
